@startuml

Actor "FrontEnd \nApp" as user
entity "FastAPI \nREST module" as pf
Boundary "Tahoe Introducer \nTestGrid" as tahoe

group User enters data
    user -> pf : submit the string "testdata"
    activate tahoe
    pf -> tahoe : (HTTPX POST) string "testdata"
    tahoe -> pf :  cap_string , 200
    deactivate tahoe
    pf -> user : "OK, here is the special URL"
end

group Next, user changes data
    user -> pf : "ref X has new data"
    activate pf
        activate tahoe
        pf -> tahoe : new value for "cap_string" is "datatest"
        tahoe -> pf : cap_string , 201
        deactivate tahoe
        pf -> user : "data updated"
    deactivate pf
end
@enduml